blank_issues_enabled: false

# contact_links:

  - name: Questions/Support (Discussions)
    url: https://github.com/<org>/<repo>/discussions
    about: For how-to questions, use Discussions instead of issues.  

